### ISSUE TITLE
"Malformed floating point number" while reading GRDECL file

### ISSUE THREAD

**Issue by rafaelmarch3** [OPM/opm-upscaling#360]
I'm trying to test upscale_perm with the following GRDECL file:

```
SPECGRID
3 4 5 1 F /

COORD
COORD.dat /

ZCORN
ZCORN.dat /

PERMX
PERMX.dat /

PERMY
PERMY.dat /

PERMZ
PERMZ.dat /

PORO
PORO.dat /

ACTNUM
ACTNUM.dat /
```

I get the following error:

```
Parsing Eclipse file </mnt/d/core-ups/opm-wsl/daily_work/2022_07_21/problem_floating_point/scripting_example/out/simple.grdecl> ... Program threw an exception: Problem with keyword COORD
In /mnt/d/core-ups/opm-wsl/daily_work/2022_07_21/problem_floating_point/scripting_example/out/simple.grdecl line 4.
Internal error: Malformed floating point number 'COORD.dat'
terminate called after throwing an instance of 'std::_Nested_exception<Opm::OpmInputError const>'
  what():  Problem with keyword COORD
```

However, if I copy the contents of COORD.dat file into the GRDECL, everything works normally. I'm not sure it is related to line endings in Linux/Windows, since I'm using OPM within WSL (Windows Subsystem for Linux). Any ideas about what might be happening?

Thanks!
Rafael March.

**Comment by bska** [comment]
Hi Rafael,

This is one of the aspects that the file format is rather picky about.  The format expects, for example, that the `PORO` keyword is followed directly by a an optional comment block and then a sequence of floating point numbers, e.g.,
```
PORO
-- This is the porosity field
0.1 0.2 0.3 0.4
-- ...
/
```
whereas you've placed filenames into the argument instead.  I suppose we could endeavor to extend the syntax to support that format&mdash;in fact I'd like to have that ability&mdash;but for now the best course of action is to put the property keyword (e.g., `PORO`) into the property file (`PORO.dat`) and to use the `INCLUDE` keyword to input the property data instead.  In other words, instead of
```
PORO
PORO.dat /
-- ...
```
you'd have a `PORO.dat` that starts with the keyword `PORO` and write your `GRDECL` file as follows
```
SPECGRID
3 4 5 1 F /

INCLUDE
'COORD.dat' /

INCLUDE
'ZCORN.dat' /

INCLUDE
'PERMX.dat' /

INCLUDE
'PERMY.dat' /

INCLUDE
'PERMZ.dat' /

INCLUDE
'PORO.dat' /

INCLUDE
'ACTNUM.dat' /
```

**Comment by bska** [comment]
There have been no comments here for more than a year so I'm closing the issue.  Please open another issue if you have further questions.
